blank_issues_enabled: false
contact_links:
  - name: AIOStreams Community Support
    url: https://github.com/Viren070/AIOStreams/discussions/categories/help
    about: If you need help, create a new post here with your question.

